Traceback (most recent call last):
  File "/home/steven/ros2_ws/src/my_robot_socket_node/setup.py", line 5, in <module>
    setup(
  File "/home/steven/.local/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/home/steven/.local/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/home/steven/.local/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/home/steven/.local/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 968, in run_commands
    self.run_command(cmd)
  File "/home/steven/.local/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/home/steven/.local/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.run()
  File "/home/steven/.local/lib/python3.10/site-packages/setuptools/command/install.py", line 68, in run
    return orig.install.run(self)
  File "/home/steven/.local/lib/python3.10/site-packages/setuptools/_distutils/command/install.py", line 709, in run
    self.run_command(cmd_name)
  File "/home/steven/.local/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
    self.distribution.run_command(command)
  File "/home/steven/.local/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/home/steven/.local/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.run()
  File "/home/steven/.local/lib/python3.10/site-packages/setuptools/command/install_scripts.py", line 35, in run
    bs_cmd = self.get_finalized_command('build_scripts')
  File "/home/steven/.local/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 305, in get_finalized_command
    cmd_obj = self.distribution.get_command_obj(command, create)
  File "/home/steven/.local/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 859, in get_command_obj
    klass = self.get_command_class(command)
  File "/home/steven/.local/lib/python3.10/site-packages/setuptools/dist.py", line 952, in get_command_class
    eps = metadata.entry_points(group='distutils.commands', name=command)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 1021, in entry_points
    return SelectableGroups.load(eps).select(**params)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 487, in select
    return self._all.select(**params)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 359, in select
    return EntryPoints(ep for ep in self if ep.matches(**params))
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 359, in <genexpr>
    return EntryPoints(ep for ep in self if ep.matches(**params))
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 231, in matches
    attrs = (getattr(self, param) for param in params)
TypeError: 'dict_keyiterator' object is not callable
